SELECT sum(salary) as "총액", avg(salary) as "평균", max(salary) as "최대", min(salary) as "최소" from employee;

SELECT COUNT(*) AS "사원 수" FROM EMPLOYEE;

-- DISTINCT : 중복 제거
SELECT COUNT(DISTINCT JOB) AS "직업 종류 갯수" FROM EMPLOYEE;

SELECT DNO AS "부서 번호", AVG(SALARY) AS "급여평균" FROM EMPLOYEE GROUP BY DNO;

SELECT DNO, JOB, COUNT(*), SUM(SALARY) FROM EMPLOYEE GROUP BY DNO, JOB ORDER BY DNO, JOB;

SELECT DNO, MAX(SALARY) FROM EMPLOYEE GROUP BY DNO HAVING MAX(SALARY) >= 1000;

SELECT ENO AS "직원 번호", ENAME AS "직원 이름", JOB AS "직업", MANAGER AS "매니저 번호", HIREDATE AS "고용일", SALARY AS "급여", COMMISSION AS "비고", EMPLOYEE.DNO AS "부서 번호", DNAME AS "부서 이름", LOC AS "위치" FROM EMPLOYEE, DEPARTMENT WHERE EMPLOYEE.DNO = DEPARTMENT.DNO;

-- 알리아스(Alias) : 명령어 단축
SELECT E.ENO, E.ENAME, D.DNAME, D.LOC, E.DNO FROM EMPLOYEE E, DEPARTMENT D WHERE E.DNO = D.DNO AND E.ENO = 7788;
SELECT E.ENO, E.ENAME, D.DNAME,D.LOC, DNO FROM EMPLOYEE E JOIN DEPARTMENT D USING(DNO) WHERE E.ENO = 7788;
SELECT E.ENO, E.ENAME, D.DNAME,D.LOC, E.DNO FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DNO = D.DNO WHERE E.ENO = 7788;

SELECT E.ENAME, D.DNAME, E.SALARY, S.GRADE FROM EMPLOYEE E, DEPARTMENT D, SALGRADE S WHERE E.DNO = D.DNO AND E.SALARY BETWEEN LOSAL AND HISAL;

SELECT ENAME, DNO FROM EMPLOYEE WHERE DNO = (SELECT DNO FROM EMPLOYEE WHERE ENAME = 'SCOTT');

SELECT ENAME FROM EMPLOYEE WHERE ENO IN (SELECT ENO FROM EMPLOYEE WHERE MANAGER IS NULL);

-- <> : 다르다
SELECT ENO, ENAME, JOB, SALARY FROM EMPLOYEE WHERE SALARY < ALL (SELECT SALARY FROM EMPLOYEE WHERE JOB='SALESMAN') AND JOB <> 'SALESMAN';
