/*
-- 테이블 복사하여 생성
CREATE TABLE DEPT_COPY AS SELECT * FROM DEPARTMENT;

UPDATE DEPT_COPY SET LOC=(SELECT LOC FROM DEPT_COPY WHERE DNO=20) WHERE DNO=10;

--View (가상 테이블)
CREATE OR REPLACE VIEW V_EMP (사원, 사원이름, 부서번호, 담당업무) AS SELECT ENO, ENAME, DNO, JOB FROM EMPLOYEE WHERE JOB LIKE 'SALESMAN';

DROP VIEW V_EMP;
*/

--PL/SQL
SET SERVEROUTPUT ON 
DECLARE 
    V_ENO NUMBER(4); --변수선언
    V_ENAME EMPLOYEE.ENAME%TYPE;
    
BEGIN
    V_ENO := 7788; --초기화
    V_ENAME := 'SCOTT';
    DBMS_OUTPUT.PUT_LINE('사원번호      사원이름');
    DBMS_OUTPUT.PUT_LINE('---------------------------');
    DBMS_OUTPUT.PUT_LINE(V_ENO||'       '||V_ENAME);
END;